"""Add grid_columns to Layout

Revision ID: 5fd001b7b4f9
Revises: fa953ed2315d
Create Date: 2024-11-19 21:21:43.680199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd001b7b4f9'
down_revision = 'fa953ed2315d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grid_columns', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('layout', schema=None) as batch_op:
        batch_op.drop_column('grid_columns')

    # ### end Alembic commands ###
