"""Initial migration after reset

Revision ID: a96d17725c92
Revises: 
Create Date: 2024-11-27 19:56:58.606850

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'a96d17725c92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        # Add the column with a default for existing rows
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
        batch_op.create_index('idx_forum_post_user_id', ['user_id'], unique=False)

    # Remove the default now that the column has been added
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.alter_column('updated_at', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_index('idx_forum_post_user_id')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
